### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by wattlebird** [wattlebird/ranking#5]
- [x] Draw probability in TrueSkill
- [x] Test trueskill using other library
- [x] Implement Glicko 2
- [x] Test Glicko 2 using other library
- [x] Concept "rating period" should reflect in "time" column in Table
- [x] Adapt unsupervised ranking API to next generation
- [x] Weight, time and hostavantage must be applied in all three TimeSeriesRankers
- [x] Comments
- [x] Deprecate 'hostavantage'
- [x] Docs
